
package com.econetwireless.in.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IntelligentNetworkServiceImpl", targetNamespace = "http://service.soap.in.econetwireless.com/", wsdlLocation = "http://localhost:8888/intelligent-network-api/IntelligentNetworkService?wsdl")
public class IntelligentNetworkServiceImpl
    extends Service
{

    private final static URL INTELLIGENTNETWORKSERVICEIMPL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.econetwireless.in.soap.service.IntelligentNetworkServiceImpl.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.econetwireless.in.soap.service.IntelligentNetworkServiceImpl.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/intelligent-network-api/IntelligentNetworkService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/intelligent-network-api/IntelligentNetworkService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTELLIGENTNETWORKSERVICEIMPL_WSDL_LOCATION = url;
    }

    public IntelligentNetworkServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntelligentNetworkServiceImpl() {
        super(INTELLIGENTNETWORKSERVICEIMPL_WSDL_LOCATION, new QName("http://service.soap.in.econetwireless.com/", "IntelligentNetworkServiceImpl"));
    }

    /**
     * 
     * @return
     *     returns IntelligentNetworkService
     */
    @WebEndpoint(name = "IntelligentNetworkPort")
    public IntelligentNetworkService getIntelligentNetworkPort() {
        return super.getPort(new QName("http://service.soap.in.econetwireless.com/", "IntelligentNetworkPort"), IntelligentNetworkService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntelligentNetworkService
     */
    @WebEndpoint(name = "IntelligentNetworkPort")
    public IntelligentNetworkService getIntelligentNetworkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.in.econetwireless.com/", "IntelligentNetworkPort"), IntelligentNetworkService.class, features);
    }

}
